name: Build and Push to Arvan

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Arvan Registry
        uses: docker/login-action@v3
        with:
          registry: registry.ir-thr-at1.arvanstorage.ir
          username: talaparsi
          password: ${{ secrets.ARVAN_PASS }}

      - name: Build image
        run: docker build -t registry.ir-thr-at1.arvanstorage.ir/talaparsi/backend:latest .

      - name: Push image
        run: docker push registry.ir-thr-at1.arvanstorage.ir/talaparsi/backend:latest
        
