name: Build and Push to Arvan

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Arvan Registry
        uses: docker/login-action@v3
        with:
          registry: registry-1f626cb39a-talaparsi.apps.ir-central1.arvancaas.ir
          username: ${{ secrets.ARVAN_USERNAME }}
          password: ${{ secrets.ARVAN_PASS }}

      - name: Build image
        run: docker build -t registry-1f626cb39a-talaparsi.apps.ir-central1.arvancaas.ir/backend:latest .

      - name: Push image
        run: docker push registry-1f626cb39a-talaparsi.apps.ir-central1.arvancaas.ir/backend:latest
